// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6m2xsS7LAqW3M0S03Y15Clr-doKzfnW0',
    appId: '1:22766110884:web:a2f429d89216caeb8afe31',
    messagingSenderId: '22766110884',
    projectId: 'corporate-app-b7bed',
    authDomain: 'corporate-app-b7bed.firebaseapp.com',
    storageBucket: 'corporate-app-b7bed.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMIKLvd3lgI_E0Xr66oJN5vY4XQf4fM0g',
    appId: '1:22766110884:android:f64c43f9ebf91fb68afe31',
    messagingSenderId: '22766110884',
    projectId: 'corporate-app-b7bed',
    storageBucket: 'corporate-app-b7bed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJzsNoiHw4H0E-TZLM9uXF8KqahIAinHQ',
    appId: '1:22766110884:ios:703b91b27aef8c828afe31',
    messagingSenderId: '22766110884',
    projectId: 'corporate-app-b7bed',
    storageBucket: 'corporate-app-b7bed.firebasestorage.app',
    iosBundleId: 'com.example.corporateApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJzsNoiHw4H0E-TZLM9uXF8KqahIAinHQ',
    appId: '1:22766110884:ios:703b91b27aef8c828afe31',
    messagingSenderId: '22766110884',
    projectId: 'corporate-app-b7bed',
    storageBucket: 'corporate-app-b7bed.firebasestorage.app',
    iosBundleId: 'com.example.corporateApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6m2xsS7LAqW3M0S03Y15Clr-doKzfnW0',
    appId: '1:22766110884:web:6ea08211e7ac15678afe31',
    messagingSenderId: '22766110884',
    projectId: 'corporate-app-b7bed',
    authDomain: 'corporate-app-b7bed.firebaseapp.com',
    storageBucket: 'corporate-app-b7bed.firebasestorage.app',
  );
}
